title = "Atlas"

[server]
port = 8080

[db]
driver = "postgres"
host = "localhost"
port = 5432
username = "admin"
password = "password"
database = "atlas_db"
sslmode = "disable"
migrationPath = "./migrations"
