database:
  host: "localhost"
  port: 5432
  name: "atlas_db"
  user: "admin"
  password: "password"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
logging:
  level: "debug"
  pretty: true
security:
  jwt_secret: "development-jwt-secret-key-not-for-production"
  bcrypt_cost: 10 # Lower cost for faster development
