server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30
  write_timeout: 30
database:
  host: "localhost"
  port: 5432
  name: "atlas_identity"
  user: "atlas"
  password: "atlas"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
logging:
  level: "info"
  pretty: true
security:
  jwt_secret: "your-super-secret-jwt-key-change-in-production-please"
  bcrypt_cost: 12
  token_ttl: 900 # 15 minutes
  refresh_ttl: 86400 # 24 hours
